# Generated by Django 6.0.2 on 2026-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_crypto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.IntegerField()),
                ('contact_link', models.URLField()),
            ],
        ),
    ]
